// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfeipxfyvimsjbsljpvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZWlweGZ5dmltc2pic2xqcHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDQyMjQsImV4cCI6MjA1MDEyMDIyNH0.ylrCt43F76ibA6RZRyzm0X1-tzXHpPoG-7zTgXVdL9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);